# This is a comment line
# Sample makefile for fraction class

main: person.cpp person.hpp stdDev.cpp 
	g++ fperson.cpp stdDev.cpp

main: person.cpp person.hpp stdDev.cpp 
	g++ fperson.cpp stdDev.cpp && ./a.out
	
all: 
	make main && make clean

clean:
	rm -f a.out
