# This is a comment line
# Sample makefile for fraction class

main: main.cpp findMedian.cpp 
	g++ findMedian.cpp main.cpp

test: main.cpp findMedian.cpp 
	g++ findMedian.cpp main.cpp && ./a.out

all: 
	make main && make clean

clean:
	rm -f a.out
